OS_AUTH_URL=http://172.18.11.197/identity
OS_IDENTITY_API_VERSION=3
OS_NO_CACHE=1
OS_PASSWORD=password
OS_PROJECT_DOMAIN_ID=default
OS_REGION_NAME=RegionOne
OS_USER_DOMAIN_ID=default
OS_VOLUME_API_VERSION=2

OS_USERNAME=project1_user
OS_PROJECT_NAME=project1
